import os

def menu():
    print('='*90)
    print('{:<30}'.format('AC - Acre'), end='')
    print('{:<30}'.format('AL - Alagoas'), end='')
    print('{:<30}'.format('AP - Amapá'))
    print('{:<30}'.format('AM - Amazonas'), end='')
    print('{:<30}'.format('BA - Bahia'), end='')
    print('{:<30}'.format('CE - Ceará'))
    print('{:<30}'.format('DF - Distrito Federal'), end='')
    print('{:<30}'.format('ES - Espírito Santo'), end='')
    print('{:<30}'.format('GO - Goiás'))
    print('{:<30}'.format('MA - Maranhão'), end='')
    print('{:<30}'.format('MT - Mato Grosso'), end='')
    print('{:<30}'.format('MS - Mato Grosso do Sul'))
    print('{:<30}'.format('MG - Minas Gerais'), end='')
    print('{:<30}'.format('PA - Pará'), end='')
    print('{:<30}'.format('PB - Paraíba'))
    print('{:<30}'.format('PR - Paraná'), end='')
    print('{:<30}'.format('PE - Pernambuco'), end='')
    print('{:<30}'.format('PI - Piauí'))
    print('{:<30}'.format('RJ - Rio de Janeiro'), end='')
    print('{:<30}'.format('RN - Rio Grande do Norte'), end='')
    print('{:<30}'.format('RS - Rio Grande do Sul'))
    print('{:<30}'.format('RO - Rondônia'), end='')
    print('{:<30}'.format('RR - Roraima'), end='')
    print('{:<30}'.format('SC - Santa Catarina'))
    print('{:<30}'.format('SP - São Paulo'), end='')
    print('{:<30}'.format('SE - Sergipe'), end='')
    print('{:<30}'.format('TO - Tocantins'))
